CUDA_VISIBLE_DEVICES=0 python -u train_clipreid.py --config_file configs/cloth_change/vit_clipreid.yml \
DATASETS.NAMES 'prcc' \
MODEL.STRIDE_SIZE '[12, 12]' \
MODEL.CLOTH_PROMPT True MODEL.ID_PROMPT True \
MODEL.I2T_LOSS True MODEL.I2T_CLOTH_LOSS True \
MODEL.I2T_LOSS_WEIGHT 1.0 MODEL.I2T_CLOTH_LOSS_WEIGHT 0.1 \
MODEL.STAGE2_I2T_LOSS True MODEL.STAGE2_I2T_CLOTH_LOSS False \
OUTPUT_DIR '' \
MODEL.DES_TRANS True MODEL.DES_WEIGHT 2.0 SOLVER.SEED 2025\
TEST.WEIGHT ''
